#!/bin/sh

# Simple wrapper that assumes gradle is available in the environment for this tutorial
# In a real project, this would be the actual Gradle Wrapper script generated by `gradle wrapper`

if command -v gradle >/dev/null 2>&1; then
    exec gradle "$@"
else
    echo "Error: gradle is not installed/found in PATH."
    echo "For this tutorial, please ensure gradle is installed or run within the provided Docker container."
    exit 1
fi
