name: Android CI with Docker

on:
  push:
    branches: [ "main", "feat/*", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-in-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build -t android-ci .
      
    - name: Run Gradle Build in Docker
      # Mount current directory to /app
      # Use the image built in previous step
      # Run './gradlew build'
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          android-ci \
          bash -c "chmod +x gradlew && ./gradlew build"
